spring:
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: redis_password
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/twitch_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

server:
  port: 8080

logging:
  level:
    liquibase: INFO
    org.springframework.data.redis: INFO
    io.lettuce.core: INFO

